### ISSUE TITLE
Hidden field not hidden

### ISSUE THREAD

**Issue by lal12** [Steveorevo/node-red-contrib-credentials#3]
I don't know if I am doing anything wrong. But I just setup a node-red docker (node-red v1.0) and the hidden field shows up as plaintext.

**Comment by Steveorevo** [comment]
After you save the content is it still visible?

**Comment by lal12** [comment]
Yeah I saving and reloading did not help. I also noticed that the credentials are printed in the browser debug console.

**Comment by Steveorevo** [comment]
Yes that is correct. The data is available to you because you have the correct security key. However, that data in your flow file should be encrypted. Sharing it should allow all other aspects of you flow to be viable to third parties; in exception to that specific piece of data which cannot be deciphered without your key file.

**Comment by lal12** [comment]
Yeah I get that, but as far as I unterstand the README the difference between a normal and hidden field is not how it safed but specifically whether it is displayed in the UI?

**Comment by Steveorevo** [comment]
As the read me has stated the purpose is for “...preventing inadvertent export to flows or to version control commits.” And as you’ve found out (and in the readme) it will still allow the “...value can be viewed using the debugger or when doing editor side DOM inspection. The "hidden" mode is only used to protect values from plain view”

Are you not seeing asterisks when closing and re-opening the flow?

**Comment by lal12** [comment]
> Are you not seeing asterisks when closing and re-opening the flow?

No, which is exactly the point of this issue ^^

I tried it in Chrome and Firefox.

**Comment by utaani** [comment]
![image](https://user-images.githubusercontent.com/17796/66993380-7108a300-f106-11e9-8e99-054713ae35a9.png)

on Node-RED 1.0.2

**Comment by david-j84** [comment]
I'm seeing the same behavior in 1.0.2 from previous <1.00 releases, hidden credentials are no longer hidden in the UI when *** type is selected.

**Comment by rei-vilo** [comment]
Same with Node-RED `1.0.3`.

**Comment by crxporter** [comment]
Same for me, just installed on nodered 1.0.4, plaintext not ***** In the config field

**Comment by eckilein** [comment]
Same behaviour on v1.0.6. Set field to `***hidden` and after saving the content remains visible.

**Comment by loganmc10** [comment]
Same issue in 1.1.2

**Comment by barry-luijten** [comment]
@Steveorevo : could you please verify Rolzad73's PR and merge it?
Thanks in advance!

**Comment by nirkons** [comment]
same on latest node-red... hidden field is still visible and not changed to ********

**Comment by just-grizzle** [comment]
Is this project dead? I use the fork from @Rolzad73 which includes a working fix for this problem. Works like a charm.

**Comment by Steveorevo** [comment]
Thank you for bringing this to my attention. I will process his merge request.

**Comment by Steveorevo** [comment]
Fixed in version 0.2.2, addressed commit: 

https://github.com/Steveorevo/node-red-contrib-credentials/commit/438628e0d815877549bf34db0f09300640246b41

npm and node-red updated.
