### ISSUE TITLE
Spelling bug, easy fix

### ISSUE THREAD

**Issue by eulores** [Steveorevo/node-red-contrib-credentials#6]
`propr` should probably be `props`

https://github.com/Steveorevo/node-red-contrib-credentials/blob/df46ca0f505787db2040950055fee95d77b895b1/credentials/credentials.js#L13

Please also consider switching all indentation to either spaces or tabs. Right now seems to be mixed style :-)

**Comment by Steveorevo** [comment]
Thank you; changed in commit e9bdae15f0602825ba1c4a8a70a464063cabba46. Will place into next release.
